using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.Models;

namespace Pikcube.Common.Utility;

/// <summary>
/// Event args for modifying which potions can't be generated by the merchant.
/// </summary>
/// <param name="p">The player we are generating for.</param>
/// <param name="blacklist">The current blacklist.</param>
public class MerchantPotionBlacklistArgs(Player p, PotionModel[] blacklist)
{
    /// <summary>
    /// The player visiting the merchant.
    /// </summary>
    public Player Owner { get; } = p;
    /// <summary>
    /// The original unmodified blacklist.
    /// </summary>
    public PotionModel[] OriginalBlacklist { get; } = [..blacklist];
    /// <summary>
    /// The current blacklist.
    /// </summary>
    public List<PotionModel> NewBlacklist { get; set; } = [..blacklist];
}